crack_generation:
    dimensions:
        width: 15.
        depth: 5.
        sigma: 7.
        width_stds_offset: 1.5
    path:
        step_size: 15.
        gradient_influence: 0.5
        width_update_chance: 0.02
        breakthrough_chance: 0.1
        min_distance: 10.
        min_width: 2.
        max_width_grow: 2.
        smoothing_type: moving_average
        smoothing: 2
        distance_improvement_threshold: 0.1
    trajectory:
        along_bottom_chance: 0.167
        along_diagonal_chance: 0.75
        along_side_chance: 0.083
        max_pivot_brick_widths: 5
        max_pivot_brick_heights: 7
        max_pivot_points: 6
        row_search_space_percent: 0.2
        column_search_space_percent: 0.2

dataset_generation:
    assets:
        hdris:
            - pond_bridge_night_4k.exr
            - rotes_rathaus_4k.exr
            - studio_garden_4k.exr
            - stuttgart_suburbs_4k.exr
            - urban_street_01_4k.exr
        scenes:
            - wall: Test wall
              other: []
    camera:
        object: Camera
        rotation:
            x:
                min: -0.196 # -π / 16
                max: 0.196 # π / 16
            y:
                min: 0.
                max: 0.
            z:
                min: -0.196 # -π / 16
                max: 0.196 # π / 16
        translation:
            x:
                min: -0.1
                max: 0.1
            y:
                min: 1
                max: 4
            z:
                min: -0.1
                max: 0.1
    label:
        resolution:
            x: 224
            y: 224
        patches: 3
        min_active_pixels: 200
        threshold:
            crack: 0.005
            ao: 0.43
