crack_generation_parameters: 
    crack_dimension_parameters: 
        width: 8.
        depth: 50.
        depth_resolution: 5
        sigma: 0.3
        width_stds_offset: 2.
    crack_path_parameters: 
        step_size: 3.
        gradient_influence: 0.5
        width_update_chance: 0.1
        breakthrough_chance: 0.1
        min_distance: 5.
        min_width: 2.
        max_width_grow: 0.2
        max_width_grow_factor: 0.2
        start_pointiness: 0
        end_pointiness: 2
        smoothing_type: moving_average
        smoothing: 4
        distance_improvement_threshold: 0.1
    crack_trajectory_parameters: 
        along_bottom_chance: 0.167
        along_diagonal_chance: 0.75
        along_side_chance: 0.083
        max_pivot_brick_widths: 5
        max_pivot_brick_heights: 7
        max_pivot_points: 6
        row_search_space_percent: 0.2
        column_search_space_percent: 0.2

scene_generation_parameters: 
    assets:
        safe_collections:
            - Base assets
            - Base assets 2
            - Walls
            - Walls 2
        hdris:
            - pond_bridge_night_4k.exr
            - rotes_rathaus_4k.exr
            - studio_garden_4k.exr
            - stuttgart_suburbs_4k.exr
            - urban_street_01_4k.exr
        materials: 
            - Gray brick - white mortar
            - Red brick - white mortar
            - Red brick - brown mortar
            - Yellow brick - gray mortar
        scenes:
            - wall: Door wall
              other:
                  - Pavement 2
                  - Plastic door
              wall_properties: 
                  brick_width: 0.21
                  brick_height: 0.05
                  mortar_size: 0.01
            - wall: Base wall
              other:
                  - Pavement
              wall_properties: 
                  brick_width: 0.21
                  brick_height: 0.05
                  mortar_size: 0.01
    camera_parameters:
        object: Camera
        rotation:
            x:
                min: -0.196 # -π / 16
                max: 0.196 # π / 16
            y:
                min: 0.
                max: 0.
            z:
                min: -0.196 # -π / 16
                max: 0.196 # π / 16
        translation:
            x:
                min: -0.2
                max: 0.2
            y:
                min: -1.5
                max: -0.5
            z:
                min: -0.2
                max: 0.2
    label_generation:
        patches: 1
        thresholding:
            min_active_pixels: 30
            image_threshold: 0.25
            uv_threshold: 0.1
            ao_threshold: 0.25
